#!/bin/sh

# A small POSIX compliant script to toggle between dark and light variant
# of a theme for GNOME/GTK based applications.

# Copyright (C) 2021 Rifaz Nahiyan
# This code is licensed under the MIT License.
# View the license in its entirety at: https://opensource.org/licenses/MIT

SCRIPTNAME="${0##*/}"
SCRIPTNAME="${SCRIPTNAME%.sh}"
SYS_CONFIG="/etc/dark-toggle/config"
USER_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/dark-toggle/config"

variant_found=
warnings=

# Theming functions

get_current_theme () {
	gsettings get org.gnome.desktop.interface gtk-theme | tr --delete \'
}

set_theme () {
	gsettings set org.gnome.desktop.interface gtk-theme "$1"
	# Unfortunately, gsettings always reports exit status 0
}

# Sanity checks

die () {
	# Display a formatted message, then exit with error
	printf "%s: %s\n" "${0##*/}" "${*}" >&2
	exit 1
}

print_warnings () {
	IFS=:
	printf "%s: errors while parsing the config file.\n" "${SCRIPTNAME}" >&2
	printf " - %s\n" $* >&2
	unset IFS
}

deps_check () {
	# Check dependencies. Currently, all deps are considered required.
	local deps="gsettings notify-send sed tr"
	local missing=""
	for dep in ${deps}; do
		command -v "${dep}" >/dev/null || missing="${missing} ${dep}"
	done
	if [ -n "${missing}" ]
	then
		die "Missing necessary dependencies: ${missing}"
	fi
}

theme_check () {
	local user_theme="$HOME/.themes/$1"
	local system_theme="/usr/share/themes/$1"
	[ -f "$user_theme/gtk-3.0/gtk.css" ] || [ -f "$system_theme/gtk-3.0/gtk.css" ]
}

# Configuration

parse_config () {
	local config="$1"
	local current_theme="$2"

	while read left right __; do
		[ "$left" = "$current_theme" ] && alt_theme="$right" && variant="dark"
		[ "$right" = "$current_theme" ] && alt_theme="$left" && variant="light"
	done <<-EOF
		$(sed 's/#.*//' "$config" | tr --squeeze-repeats '[:blank:]')
	EOF

	printf "$alt_theme $variant"
}

main () {
	# Check if necessary and optional dependecies are there, else exit
	deps_check
	current_theme="$(get_current_theme)"

	# First, try to find the alternate variant of current theme from user config
	if [ -f "$USER_CONFIG" ]; then
		read new_theme variant <<-EOF
			$(parse_config $USER_CONFIG $current_theme)
		EOF
		variant_found="$variant (custom)"

		if ! theme_check "$new_theme"; then
			variant_found=
			warning="The user-defined variant of the current theme is not installed in the system."
			warnings="$warnings""$warning:"
		fi
	fi

	# If alternate theme not found in user config, try system config
	if [ -z "$variant_found" ] && [ -f "$SYS_CONFIG" ]; then
		read new_theme variant <<-EOF
			$(parse_config $SYS_CONFIG $current_theme)
		EOF
		variant_found="$variant"

		if ! theme_check "$new_theme"; then
			variant_found=
			warning="The alternate variant of the current theme is not installed in the system."
			warnings="$warnings""$warning:"
		fi
	fi

	# Config file is used for theme names that are not predictable, and for 
	# letting the user have custom light/dark theme combos.
	# Most themes will be guessed by the following code, since conventionally,
	# the suffixes -light and -dark are used to differentiate betwn variants.

	# If the current theme has the -dark suffix in it, replace with -light
	# Same logic for theme having suffix -light
	[ -z "$variant_found" ] && case $current_theme in
		*-[dD]ark)
			base_name="${current_theme%-[Dd]ark}"
			new_theme="$base_name"

			if ! theme_check "$new_theme"
			then
				new_theme="${base_name}-Light"
			fi

			if ! theme_check "$new_theme"
			then
				new_theme="${base_name}-light"
			fi
			;;

		*-[lL]ight)
			# new_theme="${current_theme//[lL]ight/Dark}"
			new_theme="${current_theme%[lL]ight}Dark"
			theme_check "$new_theme" || new_theme="${new_theme%Dark}dark"
			variant_found=dark
			;;

		*)
			new_theme="$current_theme"-dark
			theme_check "$new_theme" || new_theme="$current_theme"-Dark
			variant_found=dark
			;;
	esac

	[ -n "$warnings" ] && print_warnings "$warnings"

	theme_check "$new_theme" || die "The theme is not installed: ${new_theme}"
	set_theme "$new_theme"
	notify_msg="Theme switched to ${variant_found:-light} variant."
	notify-send -t 5000 "${SCRIPTNAME}" "$notify_msg"
}

main "${@}"

# vim: noexpandtab
